# Generated by Django 6.0.7 on 2026-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.TextField(max_length=100)),
                ('book_genre', models.TextField(max_length=100)),
                ('book_category', models.TextField(max_length=100)),
            ],
        ),
    ]
