# Generated by Django 6.0.7 on 2026-07-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_title',
            field=models.CharField(max_length=100),
        ),
    ]
