# Generated by Django 6.0.7 on 2026-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_book_category_alter_books_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_category',
            field=models.CharField(choices=[('unread', 'unread'), ('read', 'read'), ('dropped', 'dropped')], default='unread', max_length=20),
        ),
    ]
