# Generated by Django 6.0.7 on 2026-07-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_spotifytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_cover',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
    ]
