# Generated by Django 6.0.7 on 2026-07-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_books_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_cover',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
