# Generated by Django 6.0.7 on 2026-07-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_books_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_genre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_title',
            field=models.CharField(max_length=200),
        ),
    ]
